//! Post-run verification of event counts.
//!
//! # The Correctness Guarantee
//!
//! This is the heart of what makes this sample valuable: we verify that
//! every event generated by every worker is correctly reflected in the
//! FASTER store. If the counts don't match, something is broken — lost
//! RMW updates, corrupted records, checkpoint/recovery errors, etc.
//!
//! # How Verification Works
//!
//! 1. Sum per-worker stats into expected totals per campaign
//! 2. Read each campaign from the FASTER store
//! 3. Compare actual vs. expected for each counter field
//! 4. Report any mismatches
//!
//! # Why This Catches Bugs
//!
//! Every event is deterministically tracked. A single lost RMW shows up
//! as `expected_clicks != actual_clicks`. Unlike throughput benchmarks
//! that only measure speed, this sample measures *correctness* — the
//! property that matters most for a durable data store.
//!
//! # Async Considerations
//!
//! Verification runs after all workers have completed and the store is
//! quiescent. We use `spawn_blocking` for the reads because we need a
//! FASTER session, which is `!Send`.

use std::sync::Arc;

use faster_core::status::OperationStatus;
use faster_core::store::FasterKv;

use crate::functions::{CampaignFunctions, CampaignStats, EventInput, EventType};
use crate::workload::WorkerStats;

/// Aggregate expected totals from per-worker stats.
///
/// Returns three vectors: (expected_clicks, expected_impressions, expected_spend)
/// indexed by campaign_id.
pub fn aggregate_expected(
    worker_stats: &[WorkerStats],
    num_campaigns: usize,
) -> (Vec<u64>, Vec<u64>, Vec<u64>) {
    let mut clicks = vec![0u64; num_campaigns];
    let mut impressions = vec![0u64; num_campaigns];
    let mut spend = vec![0u64; num_campaigns];

    for ws in worker_stats {
        for i in 0..num_campaigns.min(ws.clicks.len()) {
            clicks[i] += ws.clicks[i];
            impressions[i] += ws.impressions[i];
            spend[i] += ws.spend[i];
        }
    }

    (clicks, impressions, spend)
}

/// Verify the FASTER store contents against expected totals.
///
/// Reads every campaign from the store and compares against the expected
/// values. Returns `true` if all campaigns match, `false` if any mismatch.
///
/// # Why This Runs Synchronously
///
/// This is called from within `spawn_blocking` because it needs a FASTER
/// session. The reads are sequential — we scan every campaign ID in order.
/// For a correctness check, speed doesn't matter; completeness does.
///
/// # What Gets Verified
///
/// For each campaign_id in 0..num_campaigns:
/// - clicks match
/// - impressions match
/// - spend_cents match
/// - campaign exists if any events were generated for it
/// - campaign doesn't exist if zero events were generated
pub fn verify_store(
    store: &Arc<FasterKv<CampaignFunctions>>,
    expected_clicks: &[u64],
    expected_impressions: &[u64],
    expected_spend: &[u64],
    num_campaigns: usize,
    label: &str,
) -> bool {
    let mut session = store.new_session();
    let mut mismatches = 0u64;
    let mut verified = 0u64;
    let mut missing = 0u64;
    let mut unexpected_missing = 0u64;

    // Dummy input required by the FASTER read API
    let read_input = EventInput {
        event_type: EventType::Click,
        amount: 0,
    };

    for campaign_id in 0..num_campaigns {
        let key = campaign_id as u64;
        let mut output: Option<CampaignStats> = None;

        let status = store.read(&mut session, &key, &read_input, &mut output, ());

        // Handle pending I/O — the record might be on disk
        if status == OperationStatus::Pending {
            let completed = store.complete_pending(&mut session);
            // The completed results are returned as a vec of (output, context).
            // Find our result.
            for (completed_output, _ctx) in completed {
                if completed_output.is_some() {
                    output = completed_output;
                    break;
                }
            }
        }

        let expected_total = expected_clicks[campaign_id]
            + expected_impressions[campaign_id]
            + expected_spend[campaign_id];

        match output {
            Some(actual) => {
                let mut campaign_ok = true;

                if actual.clicks != expected_clicks[campaign_id] {
                    if mismatches < 10 {
                        eprintln!(
                            "  MISMATCH campaign {campaign_id} clicks: \
                             expected={}, actual={}",
                            expected_clicks[campaign_id], actual.clicks
                        );
                    }
                    campaign_ok = false;
                }

                if actual.impressions != expected_impressions[campaign_id] {
                    if mismatches < 10 {
                        eprintln!(
                            "  MISMATCH campaign {campaign_id} impressions: \
                             expected={}, actual={}",
                            expected_impressions[campaign_id], actual.impressions
                        );
                    }
                    campaign_ok = false;
                }

                if actual.spend_cents != expected_spend[campaign_id] {
                    if mismatches < 10 {
                        eprintln!(
                            "  MISMATCH campaign {campaign_id} spend: \
                             expected={}, actual={}",
                            expected_spend[campaign_id], actual.spend_cents
                        );
                    }
                    campaign_ok = false;
                }

                if campaign_ok {
                    verified += 1;
                } else {
                    mismatches += 1;
                }
            }
            None => {
                if expected_total > 0 {
                    // Campaign should exist but doesn't — this is a real bug
                    if unexpected_missing < 10 {
                        eprintln!(
                            "  MISSING campaign {campaign_id}: expected {expected_total} events"
                        );
                    }
                    unexpected_missing += 1;
                } else {
                    // No events were generated for this campaign — correct to be absent
                    missing += 1;
                    verified += 1;
                }
            }
        }
    }

    store.dispose_session(session);

    let total_mismatches = mismatches + unexpected_missing;
    if total_mismatches > 10 {
        eprintln!(
            "  ... and {} more mismatches (showing first 10)",
            total_mismatches - 10
        );
    }

    eprintln!();
    eprintln!("  [{label}] Verification: {verified}/{num_campaigns} campaigns correct");
    if missing > 0 {
        eprintln!("  [{label}] {missing} campaigns had zero events (correctly absent)");
    }
    if total_mismatches > 0 {
        eprintln!("  [{label}] ✗ {total_mismatches} campaigns FAILED verification");
        false
    } else {
        eprintln!("  [{label}] ✓ All campaigns verified successfully");
        true
    }
}
