[package]
name = "faster-dst"
version = "0.1.0"
description = "Deterministic simulation testing framework for FASTER"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
faster-core = { path = "../faster-core", features = ["simulation"] }
rand = { version = "0.9", features = ["small_rng"] }
rand_chacha = "0.9"
tempfile = "3"

[dev-dependencies]
crc32fast = "1.5.0"

[features]
small-pages = ["faster-core/small-pages"]
