//! Fuzz target: log recovery with arbitrary segment data.
//!
//! Constructs a minimal `RecoveryPlan` pointing at a single log segment,
//! writes fuzzer-generated bytes as that segment file, and runs
//! `LogRecoveryEngine::recover_fold_over()`. This exercises the full
//! CRC-validated page parsing path — the same code where MF-1 (CRC
//! trailer corruption on full pages) was found.
//!
//! The fuzzer can discover:
//! - Panics in page boundary arithmetic
//! - CRC computation on corrupted/truncated pages
//! - Trailer parsing with adversarial valid_bytes values
//! - Integer overflow in address-to-segment mapping

#![no_main]

use arbitrary::Arbitrary;
use libfuzzer_sys::fuzz_target;
use std::io::Write;

use faster_core::address::LogicalAddress;
use faster_core::checkpoint::{
    CheckpointToken, CheckpointType, IndexRecoveryInfo, LogRecoveryInfo,
};
use faster_core::recovery::log_recovery::LogRecoveryEngine;
use faster_core::recovery::{ChecksumValidationPolicy, RecoveryPlan, RecoveryStep};

/// Fuzzer input for log recovery.
#[derive(Arbitrary, Debug)]
struct LogRecoveryInput {
    /// Raw bytes written as the segment file — represents one or more
    /// pages of the hybrid log, potentially with embedded PageTrailer
    /// CRC values.
    segment_data: Vec<u8>,
    /// Format version to use (CRC validation only for version >= 3).
    format_version: u8,
    /// Checksum policy: 0=Reject, 1=Warn, 2=Repair.
    checksum_policy: u8,
    /// Token value for the checkpoint.
    token: u128,
}

fuzz_target!(|input: LogRecoveryInput| {
    // Limit segment size to avoid OOM — real segments are 1 GiB but we
    // only need enough to exercise page parsing.
    if input.segment_data.is_empty() || input.segment_data.len() > 4 * 1024 * 1024 {
        return;
    }

    let dir = tempfile::tempdir().expect("tempdir");
    let base_dir = dir.path();

    // Write the fuzzed bytes as segment file "log.0".
    let seg_path = base_dir.join("log.0");
    {
        let mut f = std::fs::File::create(&seg_path).expect("create");
        f.write_all(&input.segment_data).expect("write");
    }

    let format_version = (input.format_version as u64).max(1);
    let policy = match input.checksum_policy % 3 {
        0 => ChecksumValidationPolicy::Reject,
        1 => ChecksumValidationPolicy::Warn,
        _ => ChecksumValidationPolicy::Reject,
    };

    // Construct addresses that map to segment 0.
    // begin_address = 0, final_address = segment_data.len().
    let data_len = input.segment_data.len() as u64;
    let begin_addr = LogicalAddress::ZERO;
    let final_addr = LogicalAddress::from(data_len);

    let plan = RecoveryPlan {
        token: CheckpointToken(input.token),
        checkpoint_type: CheckpointType::FoldOver,
        index_info: IndexRecoveryInfo {
            format_version,
            version: 1,
            table_size: 16,
            num_ht_bytes: 1024,
            num_ofb_bytes: 0,
            num_buckets: 16,
            start_logical_address: begin_addr,
            final_logical_address: final_addr,
        },
        log_info: LogRecoveryInfo {
            format_version,
            version: 1,
            checkpoint_type: CheckpointType::FoldOver,
            begin_address: begin_addr,
            flushed_until_address: final_addr,
            final_address: final_addr,
            head_address: begin_addr,
            snapshot_start_address: LogicalAddress::ZERO,
            snapshot_final_address: LogicalAddress::ZERO,
            use_snapshot_file: false,
            object_log_segment_count: 0,
        },
        session_infos: vec![],
        steps: vec![RecoveryStep::RecoverLog {
            checkpoint_type: CheckpointType::FoldOver,
            begin_address: begin_addr,
            until_address: final_addr,
        }],
    };

    let engine = LogRecoveryEngine::new()
        .with_checksum_policy(policy)
        .with_sector_size(512);

    // recover_fold_over must never panic — it should return Ok or Err.
    let _ = engine.recover_fold_over(&plan, base_dir, "log.");
});
