/* FASTER C FFI — auto-generated by cbindgen. DO NOT EDIT. */


#ifndef FASTER_H
#define FASTER_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Minimum buffer capacity for callback value buffers.
 *
 * Prevents tiny allocations when the input is very small.
 */
#define MIN_CALLBACK_BUF_CAPACITY 64

/**
 * C-compatible status codes returned by all FFI functions.
 *
 * # ABI Stability
 *
 * This enum is `#[repr(C)]` and its discriminant values are part of the
 * public ABI. New variants may be added, but existing values must never
 * change.
 */
typedef enum FasterStatus {
  /**
   * Operation completed successfully.
   */
  FasterStatus_Ok = 0,
  /**
   * Key not found in the store.
   */
  FasterStatus_NotFound = 1,
  /**
   * Operation is pending (asynchronous completion required).
   */
  FasterStatus_Pending = 2,
  /**
   * A new record was created (upsert semantics).
   */
  FasterStatus_Created = 3,
  /**
   * Record was updated in place.
   */
  FasterStatus_InPlaceUpdated = 4,
  /**
   * Record was updated via copy-on-write.
   */
  FasterStatus_CopyUpdated = 5,
  /**
   * The provided handle is invalid or has already been freed.
   */
  FasterStatus_InvalidHandle = 100,
  /**
   * One or more arguments are invalid (null pointer, bad length, etc.).
   */
  FasterStatus_InvalidArgument = 101,
  /**
   * The caller-provided buffer is too small for the result.
   */
  FasterStatus_BufferTooSmall = 102,
  /**
   * An internal error occurred (panic recovery, lock poison, etc.).
   */
  FasterStatus_InternalError = 103,
  /**
   * A checkpoint or recovery operation failed.
   */
  FasterStatus_CheckpointError = 104,
  /**
   * Session used from a thread other than the one that created it.
   */
  FasterStatus_ThreadMismatch = 105,
} FasterStatus;

/**
 * C-compatible checkpoint strategy enum.
 *
 * Maps to the internal [`CheckpointType`] used by faster-core.
 *
 * # ABI Stability
 *
 * This enum is `#[repr(C)]` and its discriminant values are part of the
 * public ABI. New variants may be added, but existing values must never
 * change.
 */
typedef enum FasterCheckpointType {
  /**
   * Flush all in-memory pages to the main log file.
   */
  FasterCheckpointType_FoldOver = 0,
  /**
   * Write a snapshot of the mutable region to a separate file.
   */
  FasterCheckpointType_Snapshot = 1,
} FasterCheckpointType;

typedef struct Option_FasterReadGetAtomicFn Option_FasterReadGetAtomicFn;

typedef struct Option_FasterReadGetFn Option_FasterReadGetFn;

typedef struct Option_FasterRmwAtomicFn Option_FasterRmwAtomicFn;

typedef struct Option_FasterRmwCopyFn Option_FasterRmwCopyFn;

typedef struct Option_FasterRmwInitialFn Option_FasterRmwInitialFn;

typedef struct Option_FasterUpsertPutAtomicFn Option_FasterUpsertPutAtomicFn;

typedef struct Option_FasterUpsertPutFn Option_FasterUpsertPutFn;

/**
 * Opaque handle returned to C callers. Never zero (0 = invalid).
 */
typedef uint64_t FasterHandle;

/**
 * Result of a successful checkpoint operation.
 *
 * The token is a 128-bit value split into high and low 64-bit halves
 * for C ABI compatibility (C does not have a standard `u128` type).
 */
typedef struct FasterCheckpointResult {
  /**
   * High 64 bits of the checkpoint token.
   */
  uint64_t token_high;
  /**
   * Low 64 bits of the checkpoint token.
   */
  uint64_t token_low;
  /**
   * Operation status.
   */
  enum FasterStatus status;
} FasterCheckpointResult;

/**
 * RMW initial callback: initialize a new value for a key that doesn't exist.
 *
 * `value_ptr` points to a pre-allocated buffer of `*value_len` bytes.
 * The callback writes the initial value and sets `*value_len` to the
 * actual number of bytes written.
 *
 * Returns 0 on success, non-zero on failure.
 */
typedef int32_t (*FasterRmwInitialFn)(const uint8_t *key_ptr,
                                      uintptr_t key_len,
                                      const uint8_t *input_ptr,
                                      uintptr_t input_len,
                                      uint8_t *value_ptr,
                                      uintptr_t *value_len);

/**
 * RMW copy-update callback: create a new value by modifying a copy of the old value.
 *
 * `new_value_ptr` points to a pre-allocated buffer of `*new_value_len` bytes.
 * The old value is provided read-only via `old_value_ptr`/`old_value_len`.
 *
 * Returns 0 on success, non-zero on failure.
 */
typedef int32_t (*FasterRmwCopyFn)(const uint8_t *key_ptr,
                                   uintptr_t key_len,
                                   const uint8_t *input_ptr,
                                   uintptr_t input_len,
                                   const uint8_t *old_value_ptr,
                                   uintptr_t old_value_len,
                                   uint8_t *new_value_ptr,
                                   uintptr_t *new_value_len);

/**
 * RMW atomic (in-place) callback: modify the value in the mutable region directly.
 *
 * Returns 0 if the update was applied in-place, non-zero if the record
 * needs to be relocated (e.g., variable-length value grew).
 */
typedef int32_t (*FasterRmwAtomicFn)(const uint8_t *key_ptr,
                                     uintptr_t key_len,
                                     const uint8_t *input_ptr,
                                     uintptr_t input_len,
                                     uint8_t *value_ptr,
                                     uintptr_t value_len);

/**
 * Upsert put callback: write an input value into the record.
 *
 * `value_ptr` is the destination buffer, `value_len` is its capacity.
 * The callback writes the value and sets `*actual_len` to the number
 * of bytes written.
 *
 * Returns 0 on success.
 */
typedef int32_t (*FasterUpsertPutFn)(const uint8_t *key_ptr,
                                     uintptr_t key_len,
                                     const uint8_t *input_ptr,
                                     uintptr_t input_len,
                                     uint8_t *value_ptr,
                                     uintptr_t value_len,
                                     uintptr_t *actual_len);

/**
 * Upsert atomic (in-place) callback: modify an existing value in-place.
 *
 * Returns 0 on success.
 */
typedef int32_t (*FasterUpsertPutAtomicFn)(const uint8_t *key_ptr,
                                           uintptr_t key_len,
                                           const uint8_t *input_ptr,
                                           uintptr_t input_len,
                                           uint8_t *value_ptr,
                                           uintptr_t value_len);

/**
 * Read get callback: extract output from a read record.
 *
 * `output_ptr` points to a caller-provided buffer of `*output_len` bytes.
 * The callback writes the output and sets `*output_len` to the actual
 * number of bytes written.
 *
 * Returns 0 on success, 1 if the buffer was too small.
 */
typedef int32_t (*FasterReadGetFn)(const uint8_t *key_ptr,
                                   uintptr_t key_len,
                                   const uint8_t *value_ptr,
                                   uintptr_t value_len,
                                   uint8_t *output_ptr,
                                   uintptr_t *output_len);

/**
 * Read atomic callback: read from a record in-place (same as ReadGetFn
 * but called for records in the mutable region).
 */
typedef FasterReadGetFn FasterReadGetAtomicFn;

/**
 * Async operation completion callback.
 *
 * Called when an asynchronous operation completes.
 * `status` is the FASTER status code, `context` is the user-provided
 * opaque context pointer.
 */
typedef void (*FasterAsyncCallbackFn)(uint8_t status, uint64_t context);

/**
 * Sentinel value representing an invalid or null handle.
 */
#define INVALID_HANDLE 0

/**
 * Create a new FASTER key-value store with default configuration.
 *
 * Returns an opaque store handle, or [`INVALID_HANDLE`] on failure.
 * The store uses an in-memory null device and cannot be checkpointed.
 * Use [`faster_open_with_path`] for checkpoint/recovery support.
 *
 * # Thread Safety
 *
 * The returned handle is safe to use from any thread.
 */
FasterHandle faster_open(void);

/**
 * Create a new FASTER key-value store backed by files in `path`.
 *
 * Returns an opaque store handle, or [`INVALID_HANDLE`] on failure
 * (e.g., if the path cannot be created or the pointer is null).
 *
 * The store uses a synchronous file device and supports checkpoint/recovery.
 *
 * # Safety
 *
 * - `path_ptr` must be a valid pointer to `path_len` bytes of UTF-8 data.
 */
FasterHandle faster_open_with_path(const uint8_t *path_ptr, uint32_t path_len);

/**
 * Destroy a FASTER store and release all resources.
 *
 * Returns [`FasterStatus::Ok`] on success, [`FasterStatus::InvalidHandle`]
 * if the handle is invalid or already closed.
 *
 * # Safety
 *
 * All sessions **must** be ended before calling this function. Using a
 * session handle after its store has been closed is undefined behavior.
 */
enum FasterStatus faster_close(FasterHandle store);

/**
 * Start a new session on the given store.
 *
 * Returns an opaque session handle, or [`INVALID_HANDLE`] if the store
 * handle is invalid.
 *
 * # Thread Safety
 *
 * The returned session handle **must only be used from the calling thread**.
 * Passing it to another thread is undefined behavior.
 */
FasterHandle faster_session_start(FasterHandle store);

/**
 * End and dispose a session.
 *
 * Returns [`FasterStatus::Ok`] on success, [`FasterStatus::InvalidHandle`]
 * if either handle is invalid.
 *
 * # Safety
 *
 * Must be called from the same thread that created the session. The session
 * handle must not be used after this call.
 */
enum FasterStatus faster_session_end(FasterHandle store, FasterHandle session_handle);

/**
 * Insert or update a key-value pair.
 *
 * # Parameters
 *
 * - `store` — Store handle from [`faster_open`].
 * - `session` — Session handle from [`faster_session_start`].
 * - `key_ptr` / `key_len` — Pointer and length of the key bytes.
 * - `val_ptr` / `val_len` — Pointer and length of the value bytes.
 *
 * # Returns
 *
 * A [`FasterStatus`] indicating the outcome. On success, one of `Ok`,
 * `Created`, `InPlaceUpdated`, or `CopyUpdated`.
 *
 * # Safety
 *
 * - `key_ptr` must be valid for reads of `key_len` bytes (or null if `key_len == 0`).
 * - `val_ptr` must be valid for reads of `val_len` bytes (or null if `val_len == 0`).
 * - Must be called from the thread that owns `session`.
 */
enum FasterStatus faster_upsert(FasterHandle store,
                                FasterHandle session,
                                const uint8_t *key_ptr,
                                uint32_t key_len,
                                const uint8_t *val_ptr,
                                uint32_t val_len);

/**
 * Read the value for a key into a caller-provided buffer.
 *
 * # Parameters
 *
 * - `store` — Store handle from [`faster_open`].
 * - `session` — Session handle from [`faster_session_start`].
 * - `key_ptr` / `key_len` — Pointer and length of the key bytes.
 * - `val_buf` / `val_buf_len` — Caller-provided output buffer and its capacity.
 * - `val_out_len` — On success, written with the actual value length (even if
 *   the buffer was too small, so the caller can retry with a larger buffer).
 *
 * # Returns
 *
 * - [`FasterStatus::Ok`] — Value copied into `val_buf`.
 * - [`FasterStatus::BufferTooSmall`] — Value exists but `val_buf_len` is too
 *   small. `*val_out_len` is set to the required size.
 * - [`FasterStatus::NotFound`] — Key does not exist.
 * - [`FasterStatus::Pending`] — Async I/O issued; call [`faster_complete_pending`].
 *
 * # Safety
 *
 * - `key_ptr` must be valid for reads of `key_len` bytes (or null if `key_len == 0`).
 * - `val_buf` must be valid for writes of `val_buf_len` bytes (or null if `val_buf_len == 0`).
 * - `val_out_len` must be a valid, non-null pointer to a `u32`.
 * - Must be called from the thread that owns `session`.
 */
enum FasterStatus faster_read(FasterHandle store,
                              FasterHandle session,
                              const uint8_t *key_ptr,
                              uint32_t key_len,
                              uint8_t *val_buf,
                              uint32_t val_buf_len,
                              uint32_t *val_out_len);

/**
 * Delete a key from the store.
 *
 * # Parameters
 *
 * - `store` — Store handle from [`faster_open`].
 * - `session` — Session handle from [`faster_session_start`].
 * - `key_ptr` / `key_len` — Pointer and length of the key bytes.
 *
 * # Returns
 *
 * [`FasterStatus::Ok`] if the key was deleted, [`FasterStatus::NotFound`]
 * if the key did not exist.
 *
 * # Safety
 *
 * - `key_ptr` must be valid for reads of `key_len` bytes (or null if `key_len == 0`).
 * - Must be called from the thread that owns `session`.
 */
enum FasterStatus faster_delete(FasterHandle store,
                                FasterHandle session,
                                const uint8_t *key_ptr,
                                uint32_t key_len);

/**
 * Read-modify-write: atomically read and replace the value for a key.
 *
 * For [`CallbackFunctions`], RMW performs full-value replacement (the input
 * becomes the new value). If the key does not exist, it is created.
 *
 * # Parameters
 *
 * - `store` — Store handle from [`faster_open`].
 * - `session` — Session handle from [`faster_session_start`].
 * - `key_ptr` / `key_len` — Pointer and length of the key bytes.
 * - `input_ptr` / `input_len` — Pointer and length of the new value bytes.
 *
 * # Returns
 *
 * A [`FasterStatus`] indicating the outcome.
 *
 * # Safety
 *
 * - `key_ptr` must be valid for reads of `key_len` bytes (or null if `key_len == 0`).
 * - `input_ptr` must be valid for reads of `input_len` bytes (or null if `input_len == 0`).
 * - Must be called from the thread that owns `session`.
 */
enum FasterStatus faster_rmw(FasterHandle store,
                             FasterHandle session,
                             const uint8_t *key_ptr,
                             uint32_t key_len,
                             const uint8_t *input_ptr,
                             uint32_t input_len);

/**
 * Drain completed asynchronous I/O operations for a session.
 *
 * Call this after receiving [`FasterStatus::Pending`] from a CRUD operation.
 * Returns the number of completed operations via `completed_out`.
 *
 * # Safety
 *
 * - `completed_out` must be a valid, non-null pointer to a `u32`.
 * - Must be called from the thread that owns `session`.
 */
enum FasterStatus faster_complete_pending(FasterHandle store,
                                          FasterHandle session,
                                          uint32_t *completed_out);

/**
 * Take a checkpoint of the current store state.
 *
 * Persists the hash index and hybrid log to `checkpoint_dir`. Returns
 * the checkpoint token as a pair of `u64` values (high/low halves of
 * a 128-bit identifier) via the output pointers.
 *
 * # Parameters
 *
 * - `store` — Store handle from [`faster_open_with_path`].
 * - `checkpoint_dir_ptr` / `checkpoint_dir_len` — UTF-8 directory path
 *   where checkpoint files will be written.
 * - `checkpoint_type` — [`FasterCheckpointType::FoldOver`] or
 *   [`FasterCheckpointType::Snapshot`].
 * - `token_high_out` / `token_low_out` — On success, written with the
 *   high/low 64-bit halves of the checkpoint token.
 *
 * # Returns
 *
 * [`FasterStatus::Ok`] on success, [`FasterStatus::CheckpointError`] on
 * failure.
 *
 * # Safety
 *
 * - `checkpoint_dir_ptr` must be a valid pointer to `checkpoint_dir_len`
 *   bytes of UTF-8 data.
 * - `token_high_out` and `token_low_out` must be valid, non-null pointers.
 */
enum FasterStatus faster_checkpoint(FasterHandle store,
                                    const uint8_t *checkpoint_dir_ptr,
                                    uint32_t checkpoint_dir_len,
                                    enum FasterCheckpointType checkpoint_type,
                                    uint64_t *token_high_out,
                                    uint64_t *token_low_out);

/**
 * Recover a store from a checkpoint.
 *
 * Restores the hash index and log from the checkpoint identified by
 * the given token (high/low 64-bit halves). The store must have been
 * created with [`faster_open_with_path`] pointing to the same directory
 * used during checkpoint.
 *
 * All sessions **must** be ended before calling this function.
 *
 * # Parameters
 *
 * - `store` — Store handle from [`faster_open_with_path`].
 * - `checkpoint_dir_ptr` / `checkpoint_dir_len` — UTF-8 directory path
 *   containing checkpoint files.
 * - `token_high` / `token_low` — The checkpoint token to recover. Pass
 *   both as `0` to recover the most recent checkpoint.
 *
 * # Returns
 *
 * [`FasterStatus::Ok`] on success, [`FasterStatus::CheckpointError`] on
 * failure.
 *
 * # Safety
 *
 * - `checkpoint_dir_ptr` must be a valid pointer to `checkpoint_dir_len`
 *   bytes of UTF-8 data.
 * - No sessions may be active on the store when this is called.
 */
enum FasterStatus faster_recover(FasterHandle store,
                                 const uint8_t *checkpoint_dir_ptr,
                                 uint32_t checkpoint_dir_len,
                                 uint64_t token_high,
                                 uint64_t token_low);

/**
 * Destroy a store handle. This is an alias for [`faster_close`].
 *
 * Provided for API symmetry with `faster_open` / `faster_destroy`.
 */
enum FasterStatus faster_destroy(FasterHandle store);

/**
 * Refresh the session epoch and complete any ready pending operations.
 *
 * # Parameters
 *
 * - `store` — Store handle from [`faster_open`].
 * - `session` — Session handle from [`faster_session_start`].
 * - `completed_out` — If non-null, written with the number of completed ops.
 *
 * # Returns
 *
 * [`FasterStatus::Ok`] on success.
 *
 * # Safety
 *
 * - `completed_out`, if non-null, must point to a valid, writable `u32`.
 */
enum FasterStatus faster_session_refresh(FasterHandle store,
                                         FasterHandle session,
                                         uint32_t *completed_out);

/**
 * Block until all pending operations on this session complete.
 *
 * # Parameters
 *
 * - `store` — Store handle from [`faster_open`].
 * - `session` — Session handle from [`faster_session_start`].
 * - `completed_out` — If non-null, written with the number of completed ops.
 *
 * # Returns
 *
 * [`FasterStatus::Ok`] on success.
 *
 * # Safety
 *
 * - `completed_out`, if non-null, must point to a valid, writable `u32`.
 */
enum FasterStatus faster_wait_for_all_pending(FasterHandle store,
                                              FasterHandle session,
                                              uint32_t *completed_out);

/**
 * Read-modify-write with user-supplied C callback function pointers.
 *
 * When callback pointers are non-null, they override the default
 * byte-slice replacement semantics for this single RMW operation.
 * Null callback pointers fall back to the standard behavior.
 *
 * # Parameters
 *
 * - `store` / `session` — Store and session handles.
 * - `key_ptr` / `key_len` — Key bytes.
 * - `input_ptr` / `input_len` — Input bytes (the modification delta).
 * - `initial_cb` — Called to initialize a new value when the key is not found.
 * - `copy_cb` — Called to create a new value by copying and modifying a read-only record.
 * - `atomic_cb` — Called for in-place update in the mutable region.
 *
 * # Returns
 *
 * A [`FasterStatus`] indicating the outcome.
 *
 * # Safety
 *
 * Same pointer requirements as [`faster_rmw`], plus callback function
 * pointers (if non-null) must be valid `extern "C"` functions.
 */
enum FasterStatus faster_rmw_ex(FasterHandle store,
                                FasterHandle session,
                                const uint8_t *key_ptr,
                                uint32_t key_len,
                                const uint8_t *input_ptr,
                                uint32_t input_len,
                                struct Option_FasterRmwInitialFn initial_cb,
                                struct Option_FasterRmwCopyFn copy_cb,
                                struct Option_FasterRmwAtomicFn atomic_cb);

/**
 * Upsert with user-supplied C callback function pointers.
 *
 * When callback pointers are non-null, they override the default
 * byte-slice replacement semantics for this single Upsert operation.
 *
 * # Parameters
 *
 * - `store` / `session` — Store and session handles.
 * - `key_ptr` / `key_len` — Key bytes.
 * - `input_ptr` / `input_len` — Input bytes (the new value data).
 * - `put_cb` — Called to write a new value.
 * - `put_atomic_cb` — Called for in-place update in the mutable region.
 *
 * # Safety
 *
 * Same pointer requirements as [`faster_upsert`], plus callback function
 * pointers (if non-null) must be valid `extern "C"` functions.
 */
enum FasterStatus faster_upsert_ex(FasterHandle store,
                                   FasterHandle session,
                                   const uint8_t *key_ptr,
                                   uint32_t key_len,
                                   const uint8_t *input_ptr,
                                   uint32_t input_len,
                                   struct Option_FasterUpsertPutFn put_cb,
                                   struct Option_FasterUpsertPutAtomicFn put_atomic_cb);

/**
 * Read with user-supplied C callback function pointers.
 *
 * When callback pointers are non-null, they override the default
 * behavior (copy value → output buffer) for this single Read operation.
 *
 * # Parameters
 *
 * - `store` / `session` — Store and session handles.
 * - `key_ptr` / `key_len` — Key bytes.
 * - `output_ptr` / `output_buf_len` — Output buffer and its capacity.
 * - `output_len` — Written with the actual output length on success.
 * - `get_cb` — Called to extract output from the read record.
 * - `get_atomic_cb` — Called for reads from the mutable region.
 *
 * # Safety
 *
 * Same pointer requirements as [`faster_read`], plus callback function
 * pointers (if non-null) must be valid `extern "C"` functions.
 */
enum FasterStatus faster_read_ex(FasterHandle store,
                                 FasterHandle session,
                                 const uint8_t *key_ptr,
                                 uint32_t key_len,
                                 uint8_t *output_ptr,
                                 uint32_t output_buf_len,
                                 uint32_t *output_len,
                                 struct Option_FasterReadGetFn get_cb,
                                 struct Option_FasterReadGetAtomicFn get_atomic_cb);

/**
 * Refresh the session's epoch, draining completed operations.
 *
 * This is an alias for [`faster_session_refresh`] provided for
 * API symmetry with the C++ `Refresh()` method.
 *
 * # Safety
 *
 * - `completed_out`, if non-null, must point to a valid, writable `u32`.
 * - Must be called from the thread that owns `session`.
 */
enum FasterStatus faster_refresh(FasterHandle store, FasterHandle session, uint32_t *completed_out);

/**
 * Create a fresh session (session continuation stub).
 *
 * In the C++ FASTER API, `ContinueSession` resumes a session from a
 * checkpoint token. This Rust implementation does not yet support true
 * session continuation, so this creates a fresh session and writes
 * serial number 0 to `serial_out`.
 *
 * # Parameters
 *
 * - `store` — Store handle from [`faster_open`].
 * - `serial_out` — If non-null, written with the serial number (always 0).
 *
 * # Returns
 *
 * A new session handle, or [`INVALID_HANDLE`] on failure.
 *
 * # Safety
 *
 * - `serial_out`, if non-null, must point to a valid, writable `u64`.
 */
FasterHandle faster_continue_session(FasterHandle store, uint64_t *serial_out);

#endif  /* FASTER_H */


